version: '3.9'

services:
  mysql:
    image: mysql:8.1
    container_name: stock_database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: stock_database
    volumes:
      - mysql_data:/var/lib/mysql

  microservice_stock:
    build:
      context: ./
    image: microservice_stock:latest
    container_name: microservice_stock
    ports:
      - "8089:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/stock_database
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_ROOT_PASSWORD}
    depends_on:
      - mysql
    restart: always
    command: ["java", "-jar", "app.jar"]

volumes:
  mysql_data: